postgres_rhel7_repo: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
postgres_packages:
  - rh-postgresql10 
  - rh-postgresql10-postgresql-server 
  - rh-postgresql10-postgresql-contrib 
  - rh-postgresql10-postgresql-libs
  - python-psycopg2
postgres_10_data_dir: /var/lib/pgsql/10/data
postgres_10_bin_path: /usr/pgsql-10/bin
postgres_service: postgresql-10.service
postgres_port: 5432
postgres_user: postgres
postgres_users:
  - name: flask
    password: redhat
    database: flask_db
    state: present
    priv: ALL
postgres_databases:
  - name: flask_db
    owner: flask
  - name: books_store
    owner: flask