---
# vars file for osp.servers
osp_servers:
  frontend:
    cloud: openstack
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: frontend
    meta:
      - { group: frontends, deployment_name: QA}
    userdata: |
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /root/.ssh/mykey.pub >> /home/cloud-user/.ssh/authorized_keys
  app1:
    cloud: openstack
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
    userdata: |
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /root/.ssh/mykey.pub >> /home/cloud-user/.ssh/authorized_keys

  app2:
    cloud: openstack
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta:
      - { group: apps, deployment_name: QA}
    userdata: |
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /root/.ssh/mykey.pub >> /home/cloud-user/.ssh/authorized_keys
  db:
    cloud: openstack
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: db
    meta:
      - { group: appdbs, deployment_name: QA}
    userdata: |
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /root/.ssh/mykey.pub >> /home/cloud-user/.ssh/authorized_keys