---
- name: add app1 host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*db$'
    line: "{{ hostvars[groups['apps'][0]].private_ip }} app1"
    state: present
  when: hostvars[groups['apps'][0]].private_ip is defined

- name: add app2 host to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*db$'
    line: "{{ hostvars[groups['apps'][1]].private_ip }} app2"
    state: present
  when: hostvars[groups['apps'][1]].private_ip is defined

- name: Install load balancer packages
  package:
    name: "{{ payload }}"
    state: present

- name: Configure haproxy load balancing
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true