- name: pass public 1 to workstation
  copy:
    src: "mykey.pub"
    dest: "/tmp/mykey.pub"

- name: pass public 2 to workstation
  copy:
    src: "openstack.pub"
    dest: "/tmp/openstack.pub"

- name: Create instances
  os_server:
    cloud: "{{ __server.value.cloud | default('openstack') }}"
    name: "{{ __server.value.name }}"
    image: "{{ __server.value.image }}"
    key_name: "{{ __server.value.key_name | default('ansible_ssh') }}"
    flavor: "{{ __server.value.flavor }}"
    security_groups: "{{ __server.value.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group={{__server.value.meta.0.group }},deployment_name={{ __server.value.meta.0.deployment_name }}"
    userdata: |
      #!/bin/bash
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /root/.ssh/mykey.pub >> /home/cloud-user/.ssh/authorized_keys
  loop: "{{ osp_servers | dict2items }}"
  loop_control:
    loop_var: __server

- name: Add floating IP to instance
  os_floating_ip:
    cloud: "{{ __server.value.cloud | default('openstack') }}"
    state: present
    reuse: yes
    server: "{{ __server.value.name }}"
    network: ext_network
    wait: true
    timeout: 200
  loop: "{{ osp_servers | dict2items }}"
  loop_control:
    loop_var: __server