- name: Create instances
  os_server:
    cloud: "{{ osp_servers.frontend.cloud | default('openstack') }}"
    name: "{{ osp_servers.frontend.name }}"
    image: "{{ osp_servers.frontend.image }}"
    key_name: "{{ osp_servers.frontend.key | default('ansible_ssh_key') }}"
    flavor: "{{ osp_servers.frontend.flavor }}"
    security_groups: "{{ osp_servers.frontend.security_group }}"
    delete_fip: yes
    wait: no
    nics:
      - net-name: int_network
    meta: "group={{osp_servers.frontend.meta.0.group }},deployment_name={{ osp_servers.frontend.meta.0.deployment_name }}"
    userdata: |
      #!/bin/bash
      curl -o /etc/yum.repos.d/ http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
      cat /root/.ssh/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
      cat /root/.ssh/mykey.pub >> /home/cloud-user/.ssh/authorized_keys

- name:
  pause:
    
- name: Add floating IP to instance
  os_floating_ip:
    cloud: "{{ __server.value.cloud | default('openstack') }}"
    state: present
    reuse: yes
    server: "{{ __server.value.name }}"
    network: ext_network
    wait: true
    timeout: 200
  loop: "{{ osp_servers | dict2items }}"
  loop_control:
    loop_var: __server