---
# tasks file for osp-facts
- block:
   - name: Fetch Instance Info
     os_server_info:
      cloud: openstack
     register: result
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }},{{ item.metadata.deployment_name }}"
      private_ip: " {{ item.private_v4 }}"
     with_items: "{{result.openstack_servers}}"