---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  copy: 
    src: internal.repo
    dest: /etc/yum.repos.d/internal.repo

- name: add other hosts to /etc/hosts
  lineinfile: /etc/hosts
    dest: /etc/hosts
    regexp: '.*db$'
    line: "{{ groups.appdbs[0] }} db"
    state: present  
